const list =   [
    {
    works_type: "movie",
    works_id: "0",
    msg: "再没钱！家里这6样旧东西也别留，别舍不得，早清楚早受益>>",
    url: "aeRdX",
    vname: "家里这6样旧东西别留",
    has_android: 0,
    has_iphone: 1,
    has_ipad: 1,
    has_iphone_pb: 1,
    has_ipad_pb: 1,
    add_time: "2021-06-23 17:55:23",
    auto_push: 1,
    push_time: "2021-06-24 15:30:00",
    tag: "0",
    imgv_url: "https://vorcdn.xiaodutv.com/misimg/2021/6/9660dae3.jpg",
    coprctl_small_window: 0,
    img_type: 0,
    imgh_url: "",
    push_os: "",
    operator: "",
    ispredownload: 0,
    downloadstatus: 0,
    live_come_from: "",
    live_menu_id: "",
    live_url: "",
    id: 103462,
    _data_log: null,
    },
    {
    works_type: "movie",
    works_id: "0",
    msg: "再没钱也不要，别舍不得>>",
    url: "aeRdX",
    vname: "家里这6样旧东西别留",
    has_android: 1,
    has_iphone: 0,
    has_ipad: 0,
    has_iphone_pb: 0,
    has_ipad_pb: 0,
    add_time: "2021-06-23 17:55:21",
    auto_push: 1,
    push_time: "2021-06-24 15:30:00",
    tag: "0",
    imgv_url: "https://vorcdn.xiaodutv.com/misimg/2021/6/329196bb.jpg",
    coprctl_small_window: 0,
    img_type: 0,
    imgh_url: "",
    push_os: "",
    operator: "",
    ispredownload: 0,
    downloadstatus: 0,
    live_come_from: "",
    live_menu_id: "",
    live_url: "",
    id: 103461,
    _data_log: null,
    },
    {
    works_type: "movie",
    works_id: "0",
    msg: "这样泡一下，立刻变得就和新的一样>>",
    url: "aeRdX",
    vname: "眼镜无论多脏多模糊",
    has_android: 1,
    has_iphone: 0,
    has_ipad: 0,
    has_iphone_pb: 0,
    has_ipad_pb: 0,
    add_time: "2021-06-24 10:04:14",
    auto_push: 1,
    push_time: "2021-06-24 15:30:00",
    tag: "0",
    imgv_url: "https://vorcdn.xiaodutv.com/misimg/2021/6/068cf840.jpg",
    coprctl_small_window: 0,
    img_type: 0,
    imgh_url: "",
    push_os: "",
    operator: "",
    ispredownload: 0,
    downloadstatus: 0,
    live_come_from: "",
    live_menu_id: "",
    live_url: "",
    id: 103460,
    _data_log: null,
    },
    {
    works_type: "movie",
    works_id: "0",
    msg: "眼镜无论多脏多模糊，放水里泡一泡，立刻变得就和新的一样，学学>>",
    url: "aeRdQ",
    vname: "眼镜无论多脏多模糊",
    has_android: 0,
    has_iphone: 1,
    has_ipad: 1,
    has_iphone_pb: 1,
    has_ipad_pb: 1,
    add_time: "2021-06-24 10:14:10",
    auto_push: 1,
    push_time: "2021-06-24 10:00:00",
    tag: "0",
    imgv_url: "https://vorcdn.xiaodutv.com/misimg/2021/6/916fc327.jpg",
    coprctl_small_window: 0,
    img_type: 0,
    imgh_url: "",
    push_os: "",
    operator: "",
    ispredownload: 0,
    downloadstatus: 0,
    live_come_from: "",
    live_menu_id: "",
    live_url: "",
    id: 103459,
    _data_log: null,
    },
    {
    works_type: "movie",
    works_id: "0",
    msg: "王思聪油腻聊天记录被曝光>>",
    url: "http://v.baidu.com/watch/6839157926975748485.html",
    vname: "首富之子为爱当舔狗",
    has_android: 1,
    has_iphone: 0,
    has_ipad: 0,
    has_iphone_pb: 0,
    has_ipad_pb: 0,
    add_time: "2021-06-23 17:49:04",
    auto_push: 1,
    push_time: "2021-06-24 12:00:00",
    tag: "0",
    imgv_url: "https://vorcdn.xiaodutv.com/misimg/2021/6/cda04ca7.jpg",
    coprctl_small_window: 0,
    img_type: 0,
    imgh_url: "",
    push_os: "",
    operator: "",
    ispredownload: 0,
    downloadstatus: 0,
    live_come_from: "",
    live_menu_id: "",
    live_url: "",
    id: 103458,
    _data_log: null,
    },
    {
    works_type: "movie",
    works_id: "0",
    msg: "王思聪苦追孙一宁四年，油腻聊天记录被曝光，首富之子为爱当舔狗>>",
    url: "http://v.baidu.com/watch/6839157926975748485.html",
    vname: "首富之子为爱当舔狗",
    has_android: 0,
    has_iphone: 1,
    has_ipad: 1,
    has_iphone_pb: 1,
    has_ipad_pb: 1,
    add_time: "2021-06-23 17:49:02",
    auto_push: 1,
    push_time: "2021-06-24 12:00:00",
    tag: "0",
    imgv_url: "https://vorcdn.xiaodutv.com/misimg/2021/6/bf3e3953.jpg",
    coprctl_small_window: 0,
    img_type: 0,
    imgh_url: "",
    push_os: "",
    operator: "",
    ispredownload: 0,
    downloadstatus: 0,
    live_come_from: "",
    live_menu_id: "",
    live_url: "",
    id: 103457,
    _data_log: null,
    },
    {
    works_type: "movie",
    works_id: "0",
    msg: "当众逼吴尊双手投降：你没资格喜欢>>",
    url: "http://v.baidu.com/watch/8906301459396003890.html",
    vname: "郑爽那些让人看不懂迷惑操作",
    has_android: 1,
    has_iphone: 0,
    has_ipad: 0,
    has_iphone_pb: 0,
    has_ipad_pb: 0,
    add_time: "2021-06-23 15:55:21",
    auto_push: 1,
    push_time: "2021-06-24 11:00:00",
    tag: "0",
    imgv_url: "https://vorcdn.xiaodutv.com/misimg/2021/6/a81a8c1a.jpg",
    coprctl_small_window: 0,
    img_type: 0,
    imgh_url: "",
    push_os: "",
    operator: "",
    ispredownload: 0,
    downloadstatus: 0,
    live_come_from: "",
    live_menu_id: "",
    live_url: "",
    id: 103456,
    _data_log: null,
    },
    {
    works_type: "movie",
    works_id: "0",
    msg: "郑爽那些让人看不懂迷惑操作，当众逼吴尊双手投降：你没资格喜欢>>",
    url: "aeRdD",
    vname: "郑爽那些让人看不懂迷惑操作",
    has_android: 0,
    has_iphone: 1,
    has_ipad: 1,
    has_iphone_pb: 1,
    has_ipad_pb: 1,
    add_time: "2021-06-23 15:55:58",
    auto_push: 1,
    push_time: "2021-06-24 11:10:00",
    tag: "0",
    imgv_url: "https://vorcdn.xiaodutv.com/misimg/2021/6/ea209f0e.jpg",
    coprctl_small_window: 0,
    img_type: 0,
    imgh_url: "",
    push_os: "",
    operator: "",
    ispredownload: 0,
    downloadstatus: 0,
    live_come_from: "",
    live_menu_id: "",
    live_url: "",
    id: 103455,
    _data_log: null,
    },
    {
    works_type: "movie",
    works_id: "0",
    msg: "女星离婚前后对比， 杨幂不爱鲜肉爱事业，王子文脱胎换骨遇真爱>>",
    url: "aeRd8",
    vname: "女星离婚前后对比",
    has_android: 0,
    has_iphone: 1,
    has_ipad: 1,
    has_iphone_pb: 1,
    has_ipad_pb: 1,
    add_time: "2021-06-23 18:14:09",
    auto_push: 1,
    push_time: "2021-06-24 11:10:00",
    tag: "0",
    imgv_url: "https://vorcdn.xiaodutv.com/misimg/2021/6/9bd36f2f.jpg",
    coprctl_small_window: 0,
    img_type: 0,
    imgh_url: "",
    push_os: "",
    operator: "",
    ispredownload: 0,
    downloadstatus: 0,
    live_come_from: "",
    live_menu_id: "",
    live_url: "",
    id: 103454,
    _data_log: null,
    },
    {
    works_type: "movie",
    works_id: "0",
    msg: "杨幂不爱鲜肉爱事业>>",
    url: "http://v.baidu.com/watch/7022913722651224861.html",
    vname: "女星离婚前后对比",
    has_android: 1,
    has_iphone: 0,
    has_ipad: 0,
    has_iphone_pb: 0,
    has_ipad_pb: 0,
    add_time: "2021-06-23 18:04:12",
    auto_push: 1,
    push_time: "2021-06-23 18:00:00",
    tag: "0",
    imgv_url: "https://vorcdn.xiaodutv.com/misimg/2021/6/9deda948.jpg",
    coprctl_small_window: 0,
    img_type: 0,
    imgh_url: "",
    push_os: "",
    operator: "",
    ispredownload: 0,
    downloadstatus: 0,
    live_come_from: "",
    live_menu_id: "",
    live_url: "",
    id: 103453,
    _data_log: null,
    },
    {
    works_type: "movie",
    works_id: "0",
    msg: "肖战被鞭子狂抽竟然是无实物表演？这表情也太到位了吧！>>",
    url: "aeRdH",
    vname: "肖战被鞭子狂抽",
    has_android: 0,
    has_iphone: 1,
    has_ipad: 1,
    has_iphone_pb: 1,
    has_ipad_pb: 1,
    add_time: "2021-06-23 16:14:09",
    auto_push: 1,
    push_time: "2021-06-23 16:10:00",
    tag: "0",
    imgv_url: "https://vorcdn.xiaodutv.com/misimg/2021/6/1106c11c.jpg",
    coprctl_small_window: 0,
    img_type: 0,
    imgh_url: "",
    push_os: "",
    operator: "",
    ispredownload: 0,
    downloadstatus: 0,
    live_come_from: "",
    live_menu_id: "",
    live_url: "",
    id: 103452,
    _data_log: null,
    },
    {
    works_type: "movie",
    works_id: "0",
    msg: "竟然是无实物表演？>>",
    url: "http://v.baidu.com/watch/04916065267874680341.html",
    vname: "肖战被鞭子狂抽",
    has_android: 1,
    has_iphone: 0,
    has_ipad: 0,
    has_iphone_pb: 0,
    has_ipad_pb: 0,
    add_time: "2021-06-23 16:04:12",
    auto_push: 1,
    push_time: "2021-06-23 16:00:00",
    tag: "0",
    imgv_url: "https://vorcdn.xiaodutv.com/misimg/2021/6/01cd6e13.jpg",
    coprctl_small_window: 0,
    img_type: 0,
    imgh_url: "",
    push_os: "",
    operator: "",
    ispredownload: 0,
    downloadstatus: 0,
    live_come_from: "",
    live_menu_id: "",
    live_url: "",
    id: 103451,
    _data_log: null,
    },
    {
    works_type: "movie",
    works_id: "0",
    msg: "张恒回击：应该去问郑爽出轨了几次>>",
    url: "http://v.baidu.com/watch/07224156108589355748.html",
    vname: "有新瓜？网友嘲张恒出轨",
    has_android: 1,
    has_iphone: 0,
    has_ipad: 0,
    has_iphone_pb: 0,
    has_ipad_pb: 0,
    add_time: "2021-06-23 14:04:12",
    auto_push: 1,
    push_time: "2021-06-23 14:00:00",
    tag: "0",
    imgv_url: "https://vorcdn.xiaodutv.com/misimg/2021/6/2e3d187d.jpg",
    coprctl_small_window: 0,
    img_type: 0,
    imgh_url: "",
    push_os: "",
    operator: "",
    ispredownload: 0,
    downloadstatus: 0,
    live_come_from: "",
    live_menu_id: "",
    live_url: "",
    id: 103450,
    _data_log: null,
    },
    {
    works_type: "movie",
    works_id: "0",
    msg: "有新瓜？网友嘲张恒出轨！张恒回击：应该去问郑爽出轨了几次！>>",
    url: "aeRdV",
    vname: "有新瓜？网友嘲张恒出轨",
    has_android: 0,
    has_iphone: 1,
    has_ipad: 1,
    has_iphone_pb: 1,
    has_ipad_pb: 1,
    add_time: "2021-06-23 14:14:09",
    auto_push: 1,
    push_time: "2021-06-23 14:10:00",
    tag: "0",
    imgv_url: "https://vorcdn.xiaodutv.com/misimg/2021/6/e1b70d73.jpg",
    coprctl_small_window: 0,
    img_type: 0,
    imgh_url: "",
    push_os: "",
    operator: "",
    ispredownload: 0,
    downloadstatus: 0,
    live_come_from: "",
    live_menu_id: "",
    live_url: "",
    id: 103449,
    _data_log: null,
    },
    {
    works_type: "movie",
    works_id: "0",
    msg: "每天坐着6小时就会早死？公务员白领可能比工人短命，你信吗！>>",
    url: "aeRd6",
    vname: "每天坐着6小时就会早死？",
    has_android: 0,
    has_iphone: 1,
    has_ipad: 1,
    has_iphone_pb: 1,
    has_ipad_pb: 1,
    add_time: "2021-06-22 17:50:23",
    auto_push: 1,
    push_time: "2021-06-24 15:30:00",
    tag: "0",
    imgv_url: "https://vorcdn.xiaodutv.com/misimg/2021/6/c227541b.jpg",
    coprctl_small_window: 0,
    img_type: 0,
    imgh_url: "",
    push_os: "",
    operator: "",
    ispredownload: 0,
    downloadstatus: 0,
    live_come_from: "",
    live_menu_id: "",
    live_url: "",
    id: 103448,
    _data_log: null,
    },
];


const hasArr = [];
const hasObj = {};

list.forEach(item => {
    
})